//! The Transaction Stream protos: message types from `nineveh-proto`, plus the gRPC
//! client generated here.
//!
//! Generated by `cargo xtask codegen`. Don't edit the files in `generated/`: change
//! the pinned protos with `scripts/sync-protos.sh` and regenerate.

pub use nineveh_proto::{aptos, indexer, transaction};

#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::restriction,
    missing_debug_implementations,
    rust_2018_idioms,
    unreachable_pub,
    unused_qualifications
)]
pub(crate) mod client {
    include!("generated/aptos.indexer.v1.rs");
}
