//! Rust message types for the Aptos Transaction Stream protos vendored under `proto/`.
//!
//! Generated by `cargo xtask codegen`. Don't edit the files in `generated/`: change the
//! pinned protos with `scripts/sync-protos.sh` and regenerate.
//!
//! This crate holds the messages only and depends on nothing but `prost`, so
//! `nineveh-decode` can read transactions without pulling in an async runtime. The
//! gRPC client lives in `nineveh-ingest`.

#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::restriction,
    missing_debug_implementations,
    rust_2018_idioms,
    unreachable_pub,
    unused_qualifications
)]
pub mod aptos {
    pub mod indexer {
        pub mod v1 {
            include!("generated/aptos.indexer.v1.rs");
        }
    }
    pub mod transaction {
        pub mod v1 {
            include!("generated/aptos.transaction.v1.rs");
        }
    }
    pub mod util {
        pub mod timestamp {
            include!("generated/aptos.util.timestamp.rs");
        }
    }
}

pub use aptos::indexer::v1 as indexer;
pub use aptos::transaction::v1 as transaction;
