//! The generated `nineveh.d.ts`.
//!
//! It exists so an editor can complete a record's fields and a table's columns, and so
//! `tsc` catches a typo before `nineveh validate` runs. It is never the checker — what
//! it says about widths and exactness is a simplification — so what's asserted here is
//! that the names line up with the project, not that the types are the whole truth.

use nineveh_config::ColumnType;
use nineveh_dsl::declarations;

fn vault() -> String {
    declarations(
        &[
            nineveh_dsl::SourceDecl {
                name: "deposits".into(),
                fields: vec![
                    ("user".into(), "address".into()),
                    ("amount".into(), "u64".into()),
                    ("memo".into(), "0x1::string::String".into()),
                ],
                has_deletes: false,
            },
            nineveh_dsl::SourceDecl {
                name: "vaults".into(),
                fields: vec![("address".into(), "address".into())],
                has_deletes: true,
            },
        ],
        &[
            nineveh_dsl::TableDecl {
                name: "balances".into(),
                key: vec![("user".into(), ColumnType::Address)],
                columns: vec![("balance".into(), ColumnType::U128)],
                readable: true,
                writable: true,
            },
            nineveh_dsl::TableDecl {
                name: "deposit_log".into(),
                key: vec![
                    ("version".into(), ColumnType::U64),
                    ("event_index".into(), ColumnType::U64),
                ],
                columns: vec![("amount".into(), ColumnType::U64)],
                readable: false,
                writable: false,
            },
        ],
    )
}

#[test]
fn a_record_gets_its_fields() {
    let dts = vault();
    assert!(dts.contains("interface DepositsRecord {"), "{dts}");
    assert!(dts.contains("user: Address"), "{dts}");
    assert!(dts.contains("amount: Int"), "{dts}");
    assert!(dts.contains("memo: string"), "{dts}");
}

/// Only a source with deletes offers `.deleted`, so `on(deposits.deleted, …)` is a
/// type error in the editor before it's a compile error.
#[test]
fn deletes_are_declared_only_where_they_happen() {
    let dts = vault();
    assert!(
        dts.contains("const vaults: Source<VaultsRecord> & { deleted: Source<VaultsRecord> }"),
        "{dts}"
    );
    assert!(
        dts.contains("const deposits: Source<DepositsRecord>\n"),
        "{dts}"
    );
    assert!(!dts.contains("deposits: Source<DepositsRecord> &"), "{dts}");
}

/// A log has no `row` and no `get`: a rule neither writes nor reads one (ADR 0019).
#[test]
fn a_log_offers_neither_row_nor_get() {
    let dts = vault();
    let log = dts
        .split("const deposit_log: {")
        .nth(1)
        .unwrap_or_default()
        .split("}\n")
        .next()
        .unwrap_or_default();
    assert!(!log.contains("row("), "{log}");
    assert!(!log.contains("get("), "{log}");
}

#[test]
fn a_readable_table_offers_both_keyed_by_its_key() {
    let dts = vault();
    assert!(
        dts.contains("row(user: Address): Writable<BalancesRow>"),
        "{dts}"
    );
    assert!(
        dts.contains("get(user: Address): BalancesRow | undefined"),
        "{dts}"
    );
}

/// The header says what the file is and that editing it is pointless.
#[test]
fn it_says_it_is_generated() {
    let dts = vault();
    assert!(dts.starts_with("// Generated by `nineveh init`."), "{dts}");
    assert!(dts.contains("it is not what checks your project"), "{dts}");
}

/// The same declarations, generated from a resolved project rather than by hand: this
/// is what `nineveh init` writes, and the only version whose names are guaranteed to
/// match what the compiler will accept.
mod from_a_project {
    use nineveh_dsl::declarations_for;
    use nineveh_testkit::vault;

    #[test]
    fn it_declares_every_source_and_table() {
        let (lock, project) = vault::project();
        let dts = declarations_for(&project, &lock);

        // Every source in the testkit's vault, with the kind of subject it is.
        for source in ["deposits", "withdrawals", "vaults", "positions", "shares"] {
            assert!(dts.contains(&format!("const {source}: Source<")), "{dts}");
        }
        // Events don't delete; resources and table items do.
        assert!(
            dts.contains("const deposits: Source<DepositsRecord>\n"),
            "{dts}"
        );
        assert!(
            dts.contains("const vaults: Source<VaultsRecord> & {"),
            "{dts}"
        );

        // Record fields come from the pinned layout, not from anything hand-written.
        assert!(dts.contains("interface DepositsRecord {"), "{dts}");
        assert!(dts.contains("user: Address"), "{dts}");
        assert!(dts.contains("amount: Int"), "{dts}");

        // A resource source's record carries `address` alongside its fields.
        assert!(dts.contains("interface VaultsRecord {"), "{dts}");

        // Every state table the project builds is declared.
        for table in &project.config().state {
            assert!(
                dts.contains(&format!("const {}: {{", table.name.as_str())),
                "{} missing\n{dts}",
                table.name
            );
        }
    }

    /// A mirror can be read but not written; a log is neither.
    #[test]
    fn what_a_handler_may_do_to_each_table() {
        let (lock, project) = vault::project();
        let dts = declarations_for(&project, &lock);
        let block = |name: &str| {
            dts.split(&format!("const {name}: {{"))
                .nth(1)
                .unwrap_or_default()
                .split("  }")
                .next()
                .unwrap_or_default()
                .to_owned()
        };
        let balances = block("balances");
        assert!(balances.contains("row("), "{balances}");
        assert!(balances.contains("get("), "{balances}");

        let vaults = block("vaults");
        assert!(!vaults.contains("row("), "{vaults}");
        assert!(vaults.contains("get("), "{vaults}");
    }
}
