[package]
name = "NinevehArena"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
arena = "_"

# For `aptos move test --dev`; publishing sets the real address.
[dev-addresses]
arena = "0xc004"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
