//! The generated `nineveh.d.ts`.
//!
//! The DSL file is real TypeScript syntax, so an editor will happily open it — but
//! without declarations it has nothing to complete. This module writes the ambient
//! declarations for one project: its sources with their record fields, its tables with
//! their columns, and the built-ins.
//!
//! It is a convenience, never the checker. `tsc` catches a misspelled field before the
//! file is saved; `nineveh validate` is what decides whether a project is correct, and
//! it checks against the lock and the real types. Where the two disagree, this file is
//! the one that's wrong. Integers are declared as `bigint` so arithmetic and `+=`
//! typecheck; exactness and width are `nineveh-expr`'s business.

use std::fmt::Write as _;

use nineveh_config::{ColumnType, Project, TableKind, record_scope};
use nineveh_decode::Lockfile;

/// One source, as the DSL sees it.
#[derive(Debug, Clone)]
pub struct SourceDecl {
    pub name: String,
    /// Field name and Move type, from the record's [`Scope`](nineveh_config::Scope).
    pub fields: Vec<(String, String)>,
    pub has_deletes: bool,
}

/// One table a handler can write or read.
#[derive(Debug, Clone)]
pub struct TableDecl {
    pub name: String,
    pub key: Vec<(String, ColumnType)>,
    pub columns: Vec<(String, ColumnType)>,
    /// Whether a rule may read a row of it. A `log` can't be (ADR 0019), so it gets
    /// no `get`.
    pub readable: bool,
    /// Whether a handler in this file may write it: true for the tables the file
    /// declares. A `mirror` is written by its source, and a `log` by its events.
    pub writable: bool,
}

/// Write the ambient declarations for a project.
#[must_use]
pub fn declarations(sources: &[SourceDecl], tables: &[TableDecl]) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by `nineveh init`. Do not edit — it is rewritten from\n\
         // nineveh.yaml and nineveh.lock, and it is not what checks your project.\n\n\
         declare global {\n",
    );

    out.push_str("  /** An Aptos account address. */\n  type Address = string & { readonly __address: unique symbol }\n");
    out.push_str("  /** A Move integer. Exact width is checked by `nineveh validate`. */\n  type Int = bigint\n\n");

    for source in sources {
        let mut fields = String::new();
        for (name, ty) in &source.fields {
            let _ = writeln!(fields, "    /** `{ty}` */\n    {name}: {}", ts_move(ty));
        }
        let _ = write!(
            out,
            "  interface {} {{\n{fields}  }}\n",
            record_name(&source.name)
        );
    }
    out.push('\n');

    for table in tables {
        let mut row = String::new();
        for (name, ty) in table.key.iter().chain(&table.columns) {
            let _ = writeln!(row, "    {name}: {}", ts_column(*ty));
        }
        let _ = write!(out, "  interface {} {{\n{row}  }}\n", row_name(&table.name));
    }
    out.push('\n');

    for source in sources {
        let deleted = if source.has_deletes {
            format!(
                "  const {}: Source<{}> & {{ deleted: Source<{}> }}\n",
                source.name,
                record_name(&source.name),
                record_name(&source.name)
            )
        } else {
            format!(
                "  const {}: Source<{}>\n",
                source.name,
                record_name(&source.name)
            )
        };
        out.push_str(&deleted);
    }
    out.push('\n');

    for table in tables {
        let keys = table
            .key
            .iter()
            .map(|(name, ty)| format!("{name}: {}", ts_column(*ty)))
            .collect::<Vec<_>>()
            .join(", ");
        let get = if table.readable {
            format!(
                "    /** The row with this key, or `undefined`. */\n    get({keys}): {} | undefined\n",
                row_name(&table.name)
            )
        } else {
            String::new()
        };
        let row = if table.writable {
            format!(
                "    /** The row this rule writes. */\n    row({keys}): Writable<{}>\n",
                row_name(&table.name)
            )
        } else {
            String::new()
        };
        let _ = write!(out, "  const {}: {{\n{row}{get}  }}\n", table.name);
    }

    out.push_str(PRELUDE);
    out.push_str("}\n\nexport {}\n");
    out
}

/// The built-ins, identical for every project.
const PRELUDE: &str = r"
  interface Source<T> { readonly __record: T }
  type Writable<T> = { -readonly [K in keyof T]: T[K] } & { delete(): void }

  /** Handle every record from `source`. */
  function on<T>(source: Source<T>, handle: (record: T) => void): void

  /** The transaction the record came from. */
  const tx: { version: Int; timestamp: Int }

  function u8(x: Int): Int
  function u16(x: Int): Int
  function u32(x: Int): Int
  function u64(x: Int): Int
  function u128(x: Int): Int
  function u256(x: Int): Int
  function i8(x: Int): Int
  function i16(x: Int): Int
  function i32(x: Int): Int
  function i64(x: Int): Int
  function i128(x: Int): Int
  function i256(x: Int): Int
  function min(a: Int, b: Int): Int
  function max(a: Int, b: Int): Int
  function abs(x: Int): Int
  function address(literal: string): Address

  /** Declare a state table this file's handlers write. */
  function table<K extends object, C extends object>(shape: { key: K; columns: C }): unknown
";

fn record_name(source: &str) -> String {
    format!("{}Record", pascal(source))
}

fn row_name(table: &str) -> String {
    format!("{}Row", pascal(table))
}

fn pascal(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// A column type as TypeScript sees it.
fn ts_column(ty: ColumnType) -> &'static str {
    match ty {
        ColumnType::Bool => "boolean",
        ColumnType::Address => "Address",
        // Bytes arrive as `0x…` text, like an address without the brand.
        ColumnType::String | ColumnType::Bytes => "string",
        ColumnType::Json => "unknown",
        _ => "Int",
    }
}

/// A Move type as TypeScript sees it. Anything structured stays `unknown`: the DSL
/// reaches into it by field, and `nineveh validate` is what knows the shape.
fn ts_move(ty: &str) -> &'static str {
    match ty {
        "bool" => "boolean",
        "address" => "Address",
        "0x1::string::String" | "vector<u8>" => "string",
        t if t.starts_with('u') && t[1..].chars().all(|c| c.is_ascii_digit()) => "Int",
        _ => "unknown",
    }
}

/// The declarations for a resolved project: every source with the fields its records
/// carry, and every table with the columns it stores.
///
/// Resolution is what knows these — a record's fields come from the layouts pinned in
/// `nineveh.lock`, and a `mirror`'s columns come from its source's struct — so this
/// takes a [`Project`] rather than the config it was built from.
#[must_use]
pub fn declarations_for(project: &Project, lock: &Lockfile) -> String {
    let config = project.config();
    let sources = config
        .sources
        .iter()
        .enumerate()
        .map(|(i, source)| {
            let fields = project
                .input(nineveh_decode::SourceId(
                    u32::try_from(i).unwrap_or(u32::MAX),
                ))
                .map(|input| record_scope(lock, input, false))
                .map(|scope| {
                    scope
                        .fields
                        .into_iter()
                        .map(|(name, ty)| (name.to_string(), ty.to_string()))
                        .collect()
                })
                .unwrap_or_default();
            SourceDecl {
                name: source.name.as_str().to_owned(),
                fields,
                has_deletes: source.kind.has_deletes(),
            }
        })
        .collect::<Vec<_>>();

    let tables = config
        .state
        .iter()
        .zip(project.schemas())
        .map(|(table, schema)| {
            let (key, columns) = schema.columns.iter().enumerate().fold(
                (Vec::new(), Vec::new()),
                |(mut key, mut columns), (i, column)| {
                    let entry = (column.name.clone(), column.ty);
                    if schema.key.contains(&i) {
                        key.push(entry);
                    } else {
                        columns.push(entry);
                    }
                    (key, columns)
                },
            );
            TableDecl {
                name: table.name.as_str().to_owned(),
                key,
                columns,
                // A rule can read state, but not a log (ADR 0019).
                readable: !matches!(table.kind, TableKind::Log { .. }),
                // A `reduce` table is the only kind a handler writes. One whose rules
                // live in the YAML is offered too; the compiler still refuses it.
                writable: matches!(table.kind, TableKind::Reduce { .. }),
            }
        })
        .collect::<Vec<_>>();

    declarations(&sources, &tables)
}
